### ISSUE TITLE
socket-id keep changing for an xwidget-insert

### ISSUE THREAD

**Issue by veshboo** [jave/xwidget-emacs#16]
I found this while I am trying uzbl web browser with xwidget.

``` elisp
(require 'xwidget)
(xwidget-insert (point-min) 'socket "uzbl-core" 640  200)
(start-process "xembed2" "*xembed2*" "uzbl-core"
               "-s" "**socket-id**"
               "-u" "http://www.google.com")
```

Above xwidget-insert gives socket-id as debug message on stdout
and it keeps changing when I scroll or resize the buffer.
A plug with last socket-id seems to be displayed, but it does not last long.

At line 1049 in xwidget.c, xwidget_init_view() is called repeatedly creating
a new xwidget view even though an xwidget view (pointed by variable xv) already exists
and looked up by xwidget_view_lookup(). A bug?

**Comment by jave** [comment]
Jaesup Kwak notifications@github.com writes:

> I found this while I am trying uzbl web browser with xwidget
> 
> (require 'xwidget)
> (xwidget-insert (point-min) 'socket "uzbl-core" 640  200)
> (start-process "xembed2" "_xembed2_" "uzbl-core"
>                "-s" (**{socket-id}**)
>                "-u" "https://wwwgooglecom")
> 
> Above xwidget-insert gives socket-id on stdout and it keeps changing
> A plug with last socket-id seems to be displayed, but it does not last long
> 
> At line 1049 in xwidgetc, xwidget_init_view() is called repeatedly creating
> a new xwidget view even though an xwidget view (pointed by variable xv) already exists
> and looked up by xwidget_view_lookup() A bug?

The branches here on github arent wll maintained atm, sorry.

Have a look at the xwidget_mvp branch on Savannah if you want a browser
integrated in emacs.

Also look at the xwidget-aux repo here on Github for build information etc.

> —
> Reply to this email directly or view it on GitHub.

## 

Joakim Verona

**Comment by veshboo** [comment]
I did not know about xwidget_mvp on Savannah, I will check it. Thanks for giving me direction.
